### ISSUE TITLE
Benchmark GPU backends

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#348]
# Description

Given [the current status of Issue #93](https://github.com/diana-hep/pyhf/issues/93#issuecomment-434125138) the GPU benchmarking can start. This will include:

- [ ] Determining what key metrics to test (fit time, +others)
- [ ] Writing a benchmarking test suite (possible overlap with Issue #219)

@lukasheinrich I think that you already have some thoughts related to this, so if you have words of advice as I get started please drop them here.

# Relevant Issues and Pull Requests

- Issue #219 
- Issue #93

**Comment by kratsg** [comment]
We will need to address #332 in some way additionally. I believe the code that @dantrim provided didn't work on anything but numpy?

**Comment by matthewfeickert** [comment]
@kratsg Yeah, it was horribly slow. So that's a good point --- I'm probably getting ahead of myself.

**Comment by dantrim** [comment]
@kratsg yes the code only worked on numpy backend. attempting the tensorflow backend resulted in the error discussed in #332.

**Comment by matthewfeickert** [comment]
This is more a note to myself than anyone else, but for simple toy GPUs tests (not even pyhf related) I've found it quite easy to run out of memory on the GPU resulting in crashes.

If I run the following TensorFlow v2.0 code on my laptop

```python
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation="softmax"),
    ]
)

model.compile(
    optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
)
model.fit(x_train, y_train, epochs=10)
model.evaluate(x_test, y_test, verbose=2)
```
I can very easily exceed the GPU memory depending on what else is running and get the following

```pytb
Train on 60000 samples
Epoch 1/10
2020-01-20 00:39:58.633025: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2020-01-20 00:39:58.633417: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2020-01-20 00:39:58.633776: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2020-01-20 00:39:58.634145: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2020-01-20 00:39:58.634568: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2020-01-20 00:39:58.635456: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2020-01-20 00:39:58.635470: W tensorflow/stream_executor/stream.cc:2041] attempting to perform BLAS operation using StreamExecutor without BLAS support
2020-01-20 00:39:58.635488: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Internal: Blas GEMM launch failed : a.shape=(32, 784), b.shape=(784, 128), m=32, n=128, k=784
	 [[{{node sequential/dense/MatMul}}]]
   32/60000 [..............................] - ETA: 10:32Traceback (most recent call last):
  File "/home/feickert/Desktop/cudatoolkit-download/MNIST.py", line 35, in <module>
    model.fit(x_train, y_train, epochs=10)
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/feickert/.venvs/pyhf-dev/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError:  Blas GEMM launch failed : a.shape=(32, 784), b.shape=(784, 128), m=32, n=128, k=784
	 [[node sequential/dense/MatMul (defined at /Desktop/cudatoolkit-download/MNIST.py:35) ]] [Op:__inference_distributed_function_655]

Function call stack:
distributed_function
```

but if I [properly limit the GPU memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth)

> In some cases it is desirable for the process to only allocate a subset of the available memory, or to only grow the memory usage as is needed by the process. TensorFlow provides two methods to control this.
>
> The first option is to turn on memory growth by calling tf.config.experimental.set_memory_growth, which attempts to allocate only as much GPU memory as needed for the runtime allocations: it starts out allocating very little memory, and as the program gets run and more GPU memory is needed, we extend the GPU memory region allocated to the TensorFlow process. Note we do not release memory, since it can lead to memory fragmentation.

then the following code runs correctly

```python
import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices("GPU")
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices("GPU")
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation="softmax"),
    ]
)

model.compile(
    optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
)

model.fit(x_train, y_train, epochs=10)
model.evaluate(x_test, y_test, verbose=2)
```

Memory growth _might_ be something that either we need to watch out for or, more probably, will need to warn/remind users about.
